### ISSUE TITLE
Template uses tamague which doesn't work without expo-modules-core

### ISSUE THREAD

**Issue by krutilins** [LunatiqueCoder/luna#75]
**Describe the bug**

Error: Unable to resolve module expo-modules-core from /Users/XXX/Projects/MyAppName/node_modules/burnt/build/BurntModule.ios.js: expo-modules-core could not be found within the project or in these directories:

**To Reproduce**
1. `npx react-native init MyAppName --template @criszz77/luna`
2. `cd MyAppName` 
3. `cd ios:pods`
4. `yarn ios`

**Expected behavior**

While I research an issue, I found that [discussion](https://github.com/tamagui/tamagui/issues/459), which says that there a [library](https://github.com/sourcetoad/tamagui-react-native) specifically for pure react native.

What do you think about library? If you are not okay with that, than probably it would be better to install required expo-modules-core 

**Desktop:**
 - OS: macOS ventura
 - Version 13.1

**Smartphone:**
 - Device: iphone se 3rd generation
 - OS: iOS16.2

**Comment by LunatiqueCoder** [comment]
@krutilins You can also try to remove circumflex/caret like this:

![image](https://user-images.githubusercontent.com/55203625/227544390-0d43e8a8-02a7-4752-8c55-a1419b683dfd.png)


Then run `rm -rf node_modules ios/Pods && yarn && cd ios && pod install && cd ..`

Perhaps this will help. Or yes, you can add expo unimodules if you want to use the latest version of Tamagui with the Toasts until this gets fixed. Thank you for your patience! Sorry if this is annoying.

**Comment by LunatiqueCoder** [comment]
Should be fixed now.
