### ISSUE TITLE
yarn create luna-app fails

### ISSUE THREAD

**Issue by alariej** [LunatiqueCoder/luna#88]
**Describe the bug**
`yarn create luna-app` fails with the following error:
`error Cannot create "/usr/local/bin/create-luna-app" due to insufficient permissions.`

I then ran `yarn config set prefix ~/.local` to tame the error, which makes `yarn create luna-app` apparently succeed. The terminal shows:

success Installed "create-luna-app@3.0.3" with binaries:
      - create-luna-app
[#########...########] 113/113?
✔ What is the name of the app? · mylunaapp
✔ Choose your CLI · React Native
✔ Installed!

But mylunaapp is nowhere to be found on the machine :-(

I'm already building react-native apps on this machine.

Am I missing something obvious?

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - yarn v1.22.19

**Comment by alariej** [comment]
I had node.js installed as a snap package. Will never do that again. It screws up `npx create-react-app` as well. I re-installed node with nvm and now everything works fine.

**Comment by LunatiqueCoder** [comment]
How! Happy you figured it out fast. Let me know if you need help setting up expo-router and Next.js `app` folders together.
