### ISSUE TITLE
Problems with downloading tamagui repo

### ISSUE THREAD

**Issue by StefanEissler** [LunatiqueCoder/luna#91]
Initializing the monorepo with tamagui via the "yarn create luna-app" command, would not stop loading tamagui.
I used tamagui and React Native and Expo before. I reinstalled my yarn tool and checked the artifacts. But it still would not stop initializing tamagui. It just loads that way without stopping:

```
terminal: yarn create luna-app
yarn create v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...

success Installed "create-luna-app@3.0.3" with binaries:
      - create-luna-app
✔ What is the name of the app? · lunatestapp
✔ Choose your CLI · Expo (Monorepo) - with create-tamagui
⠏ Creating your Tamagui (@tamagui/create-tamagui) app...

```
I´m using a macbook pro 2015 with vs code.

Thank you for your help.

**Comment by LunatiqueCoder** [comment]
Hey. Basically the third option is the same as [`yarn create tamagui`](https://tamagui.dev/docs/intro/installation#quick-start). Unfortunately, this project is a little bit unmaintained at the moment, but hopefully it will get back on track starting from September.

**Comment by StefanEissler** [comment]
Okay thank you. Up and running with the tamagui template now :)

**Comment by StefanEissler** [comment]
Okay thank you. Up and running with the tamagui template now :)
